user:
        name: devops
        email: devops@nexfon.org
user_list:
        - Ali
        - Alireza
        - Amin
backuppath: "/home"
var1: true
var2: "yes"

user_list:
 - Mehdi
 - Mohsen
 - arash
tomcat_url: "https://downloads.apache.org/tomcat/tomcat-9/v9.0.50/bin/apache-tomcat-9.0.50.tar.gz"
tomcat_path: "/opt/apache-tomcat-9.0.50.tar.gz"
